# =============================================================================
# sioyek top-level Makefile
#
# A thin, Makefile-conventional wrapper around the CMake presets. CMake remains
# the source of truth; this offers familiar names for common actions.
#
# Examples:
#   ./configure --enable-lto --disable-tests   # autoconf-style options -> config.mk
#   make                                       # build (default: linux-release preset)
#   make PRESET=linux-vendored                 # or the shortcut: make linux-vendored
#   make linux-portable                        # per-preset shortcut targets
#   make test
#   make install DESTDIR=/tmp/stage
#   make options                               # list --enable/--disable/--with options
#   make distclean                             # remove build/ and all generated artifacts
#   make help                                  # list targets
#
# See cmake/README.md for the full build system documentation.
# =============================================================================

# ---- Platform detection ----------------------------------------------------
# This Makefile runs POSIX-sh recipes (it is a thin wrapper around CMake, and
# every per-preset/install/test/clean recipe relies on a POSIX shell). On
# Windows that shell is provided by Git for Windows / MSYS2 / Cygwin, which is
# also what supplies `make` itself. We therefore locate a POSIX `sh` explicitly
# and fail with actionable guidance if none exists, instead of pretending a
# PowerShell recipe translation exists (an earlier revision aliased SHELL to
# powershell.exe but kept POSIX-only recipes such as `[ -d ... ]`, `sed`, and
# `find | xargs`, which cannot work there).
#
# `cmake` is required and discovered portably: on Windows `where` resolves it,
# elsewhere `command -v`; CMake's own location is also honored via $CMAKE.

ifeq ($(OS),Windows_NT)
  HOST_IS_WINDOWS := TRUE
else
  HOST_IS_WINDOWS := FALSE
endif

# Prefer an explicitly provided CMAKE, else cmake3, else cmake.
CMAKE ?= $(shell command -v cmake3 2>/dev/null || command -v cmake 2>/dev/null)

# POSIX shell used for recipes. On Windows, GNU make's default SHELL is cmd.exe;
# point it at sh if available (Git Bash / MSYS2). We probe a few common names.
ifeq ($(HOST_IS_WINDOWS),TRUE)
  ifeq ($(origin SHELL),default)
    SHELL := $(shell (command -v sh 2>/dev/null) || (command -v bash 2>/dev/null))
  endif
endif

RM := rm -rf

# Parallelism: nproc -> sysctl -> Windows NUMBER_OF_PROCESSORS -> 1.
NPROC := $(shell (command -v nproc >/dev/null 2>&1 && nproc) \
               || (command -v sysctl >/dev/null 2>&1 && sysctl -n hw.ncpu) \
               || echo $(if $(NUMBER_OF_PROCESSORS),$(NUMBER_OF_PROCESSORS),1))

# ---- Tool sanity checks ----------------------------------------------------
# Fail early with actionable messages rather than mid-build.
ifeq ($(strip $(CMAKE)),)
  $(error cmake was not found in PATH. Install CMake >= 3.25 (presets) and re-run)
endif

ifeq ($(HOST_IS_WINDOWS),TRUE)
  ifeq ($(strip $(SHELL)),)
    $(error This Makefile drives POSIX-sh recipes. On Windows run it from a POSIX environment that provides 'sh' and 'make' (Git for Windows "Git Bash", MSYS2, or Cygwin), and ensure 'sh' is on PATH)
  endif
endif

# ---- Configuration ---------------------------------------------------------
# Default preset; override with e.g. `make PRESET=linux-vendored`.
PRESET ?= linux-release

# Build dir (matches the preset binaryDir; see CMakePresets.json).
BUILD_DIR ?= build/$(PRESET)

# Discovered configure presets, for the per-preset shortcut targets below
# (e.g. `make linux-vendored`, `make install-linux-vendored`). Derived from CMake
# so it stays in sync with CMakePresets.json; empty if cmake is unavailable.
SIOYEK_PRESETS := $(shell $(CMAKE) -D SIOYEK_PRESETS_FILE=$(CURDIR)/CMakePresets.json -P $(CURDIR)/cmake/list-build-presets.cmake 2>/dev/null)

# Extra CMake configure flags, e.g.
#   make CMAKE_EXTRA_FLAGS='-DSIOYEK_MUPDF_UNEMBED_FONTS=CJK'
CMAKE_EXTRA_FLAGS ?=


# Install staging dir; DESTDIR is honored by CMake's install step.
DESTDIR ?=
PREFIX ?=
JOBS ?= $(NPROC)

# Ensure `make` with no arguments builds (an included fragment defines other
# first targets, e.g. options.mk's `options`).
.DEFAULT_GOAL := all

# Untracked local overrides (like neovim's local.mk).
-include local.mk

# Options recorded by ./configure (autoconf-style). Generated by ./configure and
# git-ignored; absent means "no extra options". May set SIOYEK_CONFIGURE_FLAGS
# (translated -D flags) and/or PRESET.
-include config.mk

# Flags recorded by ./configure, injected into every configure step.
SIOYEK_CONFIGURE_FLAGS ?=

# `make options` help; the option table is shared with ./configure via
# cmake/parse-build-options.sh.
include cmake/options.mk

.PHONY: all build configure phony-configure test install uninstall package appimage \
        format format-check lint deps checkprefix options \
        clean distclean clean-build clean-deps clean-stage clean-packages clean-in-source \
        list-presets help

# ---- Build ------------------------------------------------------------------
all: build

build: configure
	$(CMAKE) --build --preset $(PRESET) -j$(JOBS)

configure:
	$(CMAKE) --preset $(PRESET) $(SIOYEK_CONFIGURE_FLAGS) $(CMAKE_EXTRA_FLAGS)

# ---- Per-preset shortcuts ---------------------------------------------------
# `make <preset>` builds with that preset:
#   make linux-vendored                    # instead of `make build PRESET=linux-vendored`
#   make linux-portable                    # any configure preset name works
#   make install-linux-portable DESTDIR=/tmp/stage
#   make test-linux-debug
# Options come from ./configure (see config.mk), e.g.:
#   ./configure --disable-lto && make linux-release
.PHONY: $(SIOYEK_PRESETS)
$(SIOYEK_PRESETS):
	$(CMAKE) --preset $@ $(SIOYEK_CONFIGURE_FLAGS) $(CMAKE_EXTRA_FLAGS)
	$(CMAKE) --build --preset $@ -j$(JOBS)

.PHONY: install-% test-% package-% clean-%
install-%:
	$(CMAKE) --preset $* $(SIOYEK_CONFIGURE_FLAGS) $(CMAKE_EXTRA_FLAGS)
	$(CMAKE) --build --preset $* -j$(JOBS)
	DESTDIR='$(DESTDIR)' $(CMAKE) --install build/$* $(if $(PREFIX),--prefix $(PREFIX),)

test-%:
	$(CMAKE) --preset $* $(SIOYEK_CONFIGURE_FLAGS) $(CMAKE_EXTRA_FLAGS)
	$(CMAKE) --build --preset $* -j$(JOBS)
	ctest --test-dir build/$* --output-on-failure

package-%:
	$(CMAKE) --preset $* $(SIOYEK_CONFIGURE_FLAGS) $(CMAKE_EXTRA_FLAGS)
	$(CMAKE) --build --preset $* -j$(JOBS)
	cd build/$* && cpack

clean-%:
	@if [ -d "build/$*" ]; then $(CMAKE) --build build/$* --target clean; fi

# ---- Test -------------------------------------------------------------------
test: configure
	$(CMAKE) --build --preset $(PRESET) -j$(JOBS)
	ctest --test-dir $(BUILD_DIR) --output-on-failure

# ---- Install / package ------------------------------------------------------
install: configure
	$(CMAKE) --build --preset $(PRESET) -j$(JOBS)
	DESTDIR='$(DESTDIR)' $(CMAKE) --install $(BUILD_DIR) \
	    $(if $(PREFIX),--prefix $(PREFIX),)

# Remove the files a previous `make install` wrote, using the manifest that
# `cmake --install` records (build/<preset>/install_manifest.txt).
#
# DESTDIR is honoured exactly as it is for install, so uninstalling a staged
# tree (DESTDIR=/tmp/stage) removes only the staged copies -- it can never touch
# the real system prefix as a side effect of a staged install.
#
# Files absent from disk are tolerated (the tree may already be partly removed),
# but a MISSING MANIFEST is a hard error: without it there is nothing provably
# installed, and silently doing nothing would make a stale install look removed.
uninstall:
	@if [ ! -f "$(BUILD_DIR)/install_manifest.txt" ]; then \
	    echo "error: $(BUILD_DIR)/install_manifest.txt not found." >&2; \
	    echo "       Nothing is known to be installed from PRESET=$(PRESET)." >&2; \
	    echo "       Run 'make install' first (or set PRESET/BUILD_DIR to the" >&2; \
	    echo "       build you want to uninstall)." >&2; \
	    exit 1; \
	fi
	DESTDIR='$(DESTDIR)' $(CMAKE) --build $(BUILD_DIR) --target uninstall

# `make package` uses the CMake *package preset* when this configure preset has
# one, and falls back to a bare `cpack` otherwise.
#
# WHY: the old recipe ran `cd $(BUILD_DIR) && cpack`, which ignores
# CMakePresets.json's packagePresets entirely and therefore
#   * used whatever generators CPackConfig.cmake happened to carry rather than
#     the ones the preset declares (the two could disagree silently), and
#   * passed no `--config`, so it could not work with the multi-config
#     generators (Visual Studio, Xcode) that the windows-* / macos-* presets use.
# `cpack --preset` reads the declared generators and configuration; the fallback
# keeps plain (preset-less) build directories working as before.
PACKAGE_PRESET ?= $(PRESET)

package: configure
	$(CMAKE) --build --preset $(PRESET) -j$(JOBS)
	@if $(CMAKE) -D SIOYEK_PRESETS_FILE=$(CURDIR)/CMakePresets.json \
	        -D SIOYEK_PRESET_NAME=$(PACKAGE_PRESET) \
	        -P $(CURDIR)/cmake/list-build-presets.cmake --has-package-preset >/dev/null 2>&1; then \
	    echo "cpack --preset $(PACKAGE_PRESET)"; \
	    cpack --preset $(PACKAGE_PRESET); \
	else \
	    echo "no CMake package preset named '$(PACKAGE_PRESET)'; running plain cpack in $(BUILD_DIR)"; \
	    cd $(BUILD_DIR) && cpack; \
	fi

# ---- AppImage ---------------------------------------------------------------
# Thin forwarder: all AppImage packaging logic lives in CMake
# (cmake/SioyekAppImage.cmake, enabled by the linux-appimage preset). This just
# configures that preset and builds its `appimage` target, so the same operation
# is available with pure CMake:
#   cmake --preset linux-appimage && cmake --build build/linux-appimage --target appimage
APPIMAGE_PRESET ?= linux-appimage

appimage:
	$(CMAKE) --preset $(APPIMAGE_PRESET) $(SIOYEK_CONFIGURE_FLAGS) $(CMAKE_EXTRA_FLAGS)
	$(CMAKE) --build --preset $(APPIMAGE_PRESET) --target appimage -j$(JOBS)

# ---- Code quality -----------------------------------------------------------
# Format source with clang-format (uses .clang-format at the repo root).
FORMAT_PATHS ?= pdf_viewer
format:
	@if command -v clang-format >/dev/null 2>&1; then \
	    find $(FORMAT_PATHS) \( -name '*.cpp' -o -name '*.h' -o -name '*.c' \) | \
	        xargs clang-format -i; \
	    echo "clang-format applied to $(FORMAT_PATHS)"; \
	else echo "clang-format not found"; exit 1; fi

# Check formatting without changing files (non-zero if not formatted).
format-check:
	@if command -v clang-format >/dev/null 2>&1; then \
	    find $(FORMAT_PATHS) \( -name '*.cpp' -o -name '*.h' -o -name '*.c' \) | \
	        xargs clang-format --dry-run --Werror; \
	else echo "clang-format not found"; exit 1; fi

# Static analysis with clang-tidy.
#
# clang-tidy needs a *configured* build directory: it reads compile_commands.json
# (which the presets enable via CMAKE_EXPORT_COMPILE_COMMANDS) to obtain the real
# per-translation-unit flags. Depending on the `configure` target below is
# therefore both necessary and sufficient.
#
# HISTORY: this rule previously depended on $(BUILD_DIR)/.ran-cmake, a stamp file
# that NO rule in the repository ever created -- so `make lint` always died with
# "No rule to make target .../build/<preset>/.ran-cmake" before doing anything.
# `configure` is the target that actually produces the needed artifact, so the
# dependency is now real and the target works as documented. This is covered by
# a contract test (test_make_options_contract.sh) so the stamp file cannot
# silently come back.
lint: configure
	@if command -v clang-tidy >/dev/null 2>&1; then \
	    if [ ! -f "$(BUILD_DIR)/compile_commands.json" ]; then \
	        echo "error: $(BUILD_DIR)/compile_commands.json is missing;" >&2; \
	        echo "       clang-tidy needs it (CMAKE_EXPORT_COMPILE_COMMANDS=ON)." >&2; \
	        exit 1; \
	    fi; \
	    find pdf_viewer -name '*.cpp' | \
	        xargs clang-tidy -p $(BUILD_DIR); \
	else echo "clang-tidy not found"; exit 1; fi

# ---- Dependency / sanity helpers -------------------------------------------
# Fetch the vendored mupdf submodules (and their nested thirdparty modules).
deps:
	git submodule update --init --recursive

# Warn if CMAKE_INSTALL_PREFIX differs from the cached value (neovim-style).
checkprefix:
	@if [ -f "$(BUILD_DIR)/CMakeCache.txt" ] && [ -n "$(PREFIX)" ]; then \
	    cached=$$(grep '^CMAKE_INSTALL_PREFIX:' "$(BUILD_DIR)/CMakeCache.txt" | cut -d= -f2); \
	    if [ "$$cached" != "$(PREFIX)" ]; then \
	        echo "warning: PREFIX '$(PREFIX)' != cached '$$cached'; re-run 'make configure'"; \
	    fi \
	fi

# ---- Clean ------------------------------------------------------------------
# clean: remove compiled objects of the current build dir (keeps configuration).
clean:
	@if [ -d "$(BUILD_DIR)" ]; then $(CMAKE) --build $(BUILD_DIR) --target clean; fi

# distclean: remove ALL build output: the entire build/ tree (every preset),
# stage/, packaging artifacts and in-source CMake leftovers. This is the
# Makefile-equivalent of the traditional `make distclean`. It never removes
# the hand-written Makefile or any source file.
distclean: clean-deps
	$(RM) build stage sioyek-release .qt .deps
	$(RM) *.AppImage *.deb *.rpm *.tar.gz 2>/dev/null || true
	$(RM) *.o moc_*.cpp moc_*.h qrc_*.cpp ui_*.h 2>/dev/null || true
	$(RM) sioyek sioyek_log.txt sioyek_autogen sioyek.app lib_debug lib_release 2>/dev/null || true
	$(RM) CMakeFiles Testing 2>/dev/null || true
	$(RM) CMakeCache.txt cmake_install.cmake install_manifest.txt CTestTestfile.cmake CPackConfig.cmake CPackSourceConfig.cmake 2>/dev/null || true

# clean-build: remove the ENTIRE build/ tree (all presets) + dependency residue.
clean-build: clean-deps
	$(RM) build

# clean-deps: dependency/submodule in-tree build residue only (mupdf, zlib).
# The CMake clean targets remove these too; this mirrors that behavior for the
# Makefile entry point. Submodule *sources* are never touched.
clean-deps:
	$(RM) mupdf/build mupdf/generated zlib/build

clean-stage:
	$(RM) stage

clean-packages:
	$(RM) build/appimage
	$(RM) *.AppImage *.deb *.rpm *.tar.gz 2>/dev/null || true
	$(RM) *.o moc_*.cpp moc_*.h qrc_*.cpp ui_*.h 2>/dev/null || true
	$(RM) sioyek sioyek_log.txt sioyek_autogen sioyek.app lib_debug lib_release 2>/dev/null || true

clean-in-source:
	$(RM) CMakeFiles Testing
	$(RM) CMakeCache.txt cmake_install.cmake install_manifest.txt CTestTestfile.cmake 2>/dev/null || true
	$(RM) CPackConfig.cmake CPackSourceConfig.cmake 2>/dev/null || true

# ---- Help -------------------------------------------------------------------
list-presets:
	$(CMAKE) --list-presets

help:
	@echo 'sioyek Make targets:'
	@echo '  make [PRESET=...]         build (default PRESET=linux-release)'
	@echo '  make <preset>             build with a preset, e.g. make linux-vendored'
	@echo '  make install-<preset>     build + staged install, e.g. make install-linux-portable'
	@echo '  make test-<preset>        build + ctest, e.g. make test-linux-debug'
	@echo '  make package-<preset>     build + cpack, e.g. make package-linux-release'
	@echo '  make test                 build and run CTest'
	@echo '  make install DESTDIR=...  build and staged install'
	@echo '  make uninstall            remove files a previous install wrote'
	@echo '  make package              build and run CPack'
	@echo '  make appimage             build an AppImage'
	@echo '  make clean                remove objects of the current build dir'
	@echo '  make distclean            remove ALL build output (build/ + stage/ + packages + deps)'
	@echo '  make clean-build          remove the whole build/ tree (all presets)'
	@echo '  make clean-deps           remove dependency/submodule build residue (mupdf, zlib)'
	@echo '  make format               clang-format the source tree'
	@echo '  make format-check         verify formatting (no changes)'
	@echo '  make lint                 clang-tidy analysis'
	@echo '  make deps                 fetch mupdf submodules'
	@echo '  make list-presets         list available CMake presets'
	@echo ''
	@echo '  make options              list friendly --enable/--disable/--with build options'
	@echo ''
	@echo 'Configure first (autoconf-style), then build:'
	@echo '  ./configure --enable-lto --disable-tests [--preset=linux-portable]'
	@echo '  make            # or a per-preset target, e.g. make linux-portable'
	@echo ''
	@echo 'Variables: PRESET BUILD_DIR CMAKE_EXTRA_FLAGS DESTDIR PREFIX JOBS'
